b2bWeb/Controllers/AbsentDayController.cs
using ClosedXML.Excel;
using b2bWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace b2bWeb.Controllers
{
    public class AbsentDayController : Controller
    {
        AbsentDB AbsentDB = new AbsentDB();
        AttendanceDurationDB AttendanceDurationDB = new AttendanceDurationDB();

        public ActionResult Index()
        {
            if (Session["Username"] != null && Session["CompanyID"] != null)
            {
                try
                {
                    string actionName = this.ControllerContext.RouteData.Values["controller"].ToString();

                    //if (DashboardController.Paket(actionName) == true)
                    //{

                    //}
                    //else
                    //{
                    //    return RedirectToAction("Error", "Dashboard");
                    //}

                    ViewBag.HMenu = DashboardController.HeaderMenu();
                    ViewBag.Title = "Report / Attendance";
                    return View();

                }
                catch (Exception ex)
                {
                    ex.Message.ToString();
                    return RedirectToAction("Error", "Dashboard");
                }
            }
            else
            {
                return Redirect("/");
            }
        }

        public ActionResult GetDataAttendanceDays()
        {
            string PageNumber = Request.QueryString["pageNumber"];
            string pageSize = Request.QueryString["pageSize"];
            string searchText = Request.QueryString["searchText"];

            Parameter param = new Parameter();

            param.Company_ID = Convert.ToInt32(Session["CompanyID"]);
            param.PageNumber = Convert.ToInt32(PageNumber);
            param.RowspPage = Convert.ToInt32(pageSize);
            param.Search = searchText;
            param.Get_Type = "Day";


            var Result = AttendanceDurationDB.GetDataAttendanceDuration(param) ?? new List<JsonAttendanceDuration>();

            if (Result.Count != 0)
            {
                return Json(Result[0], JsonRequestBehavior.AllowGet);
            }
            else
            {
                JsonAttendanceDuration Baru = new JsonAttendanceDuration();
                Baru.total = 0;
                Baru.rows = new List<rowsAttendanceDuration>();

                return Json(Baru, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ExportToExcel(DateTime StartDate)
        {
            if (Session["Username"] != null && Session["CompanyID"] != null)
            {
                var g = Convert.ToDateTime(StartDate.ToString("MM/dd/yyyy"));

                DataTable A = AbsentDB.AbsentDay(g);

                A.AcceptChanges();

                XLWorkbook wbook = new XLWorkbook();
                var wr = wbook.Worksheets.Add(A, "Sheet1");
                wr.Tables.FirstOrDefault().Theme = XLTableTheme.None;
                wr.Tables.FirstOrDefault().ShowAutoFilter = false;

                // Prepare the response
                HttpResponseBase httpResponse = Response;
                httpResponse.Clear();
                httpResponse.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                //Provide you file name here
                httpResponse.AddHeader("content-disposition", "attachment;filename=\"Attendance( " + g.ToString("MMMM yyyy")+").xlsx\"");

                // Flush the workbook to the Response.OutputStream
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    wbook.SaveAs(memoryStream);
                    memoryStream.WriteTo(httpResponse.OutputStream);
                    memoryStream.Close();
                }
                httpResponse.End();
                return View("");
            }
            else
            {
                return Redirect("/");
            }
        }
    }    
}

b2bWeb/Views/AbsentDay/Index.cshtml
@model b2bWeb.Models.rowsAttendanceDuration

<style>
    .datepicker {
        z-index: 1600 !important; /* has to be larger than 1050 */
    }
</style>

<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-transparent">@ViewBag.Title</div>
            <div class="card-body">
                <div class="table-responsive text-nowrap mb-1">
                    <div id="toolbar">
                        <span class="input-group-btn">
                            <a href="#" class="btn btn-outline-success my-2 my-sm-0" onclick="excel_date();">
                                <i class="fa fa-download"></i>&nbsp;Excel
                            </a>
                        </span>
                    </div>
                    <table id="table"
                           data-toggle="table"
                           data-toolbar="#toolbar"
                           data-search="true"
                           data-show-refresh="true"
                           data-show-toggle="true"
                           data-show-columns="true"
                           data-pagination="true"
                           data-side-pagination="server"
                           data-url="@Url.Action("GetDataAttendanceDays", "AbsentDay")"
                           data-query-params-type="false"
                           data-buttons-class="primary"
                           class="table table-bordered table-sm table-hover">
                        <thead>
                            <tr>
                                <th data-field="@Html.DisplayNameFor(m => m.Month)">MONTH</th>
                                <th data-field="@Html.DisplayNameFor(m => m.Visit_NIK)">NIK</th>
                                <th data-field="@Html.DisplayNameFor(m => m.Employee_Name)">EMPLOYEE</th>
                                <th data-field="@Html.DisplayNameFor(m => m.TotalDay)">TOTAL DAYS</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@{ Html.RenderPartial("_ScriptTable"); }


<div class="modal fade" id="myModal_excel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#6183ff;">
                <h5 class="modal-title" id="myModalLabel" style="color: #ffffff">Export to Excel @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            </div>
            @using (Html.BeginForm("ExportToExcel", "AbsentDay", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <label for="" class="text-uppercase">Periode</label>
                        <div>
                            <input type="text" class="form-control" id="dateMonth" name="startDate" required autocomplete="off">
                        </div>
                    </div>
                    @*<div class="form-group">
                        <label for="" class="text-uppercase">End Date</label>
                        <div>
                            <input type="text" class="form-control" id="endDate" name="endDate" required autocomplete="off">
                        </div>
                    </div>*@
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-success ex">Excel</button>
                    <button class="btn btn-primary exL d-none" type="button" disabled>
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                        Loading...
                    </button>
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>